8select/shopware-plugin-sob

- CseEightselectBasic/Resources/views/frontend/index/header.tpl
**Jira Issue**
https://8select.atlassian.net/browse/CSE-869
**Summary**
* use more consistent naming strategy for widget config and plugin api objects
**Checklist**
> CSE-869 wgt ldr config object name

- CseEightselectBasic/Components/AWSUploader.php
- CseEightselectBasic/Resources/views/frontend/checkout/finish.tpl
- CseEightselectBasic/Resources/views/frontend/index/header.tpl
- bin/release.sh
**Jira Issue**
https://8select.atlassian.net/browse/CSE-887
**Summary**
- added `staging` argument to `bin/release.sh` so that endpoints will be rewritten to staging settings
**Checklist**
> CSE-887 release for staging

- CseEightselectBasic/CseEightselectBasic.php
**Jira Issue**
https://8select.atlassian.net/browse/CSE-863
**Summary**
- reintegrated the fields `beschreibung2` and `sonstiges`
- updated description texts for several fields, see JIRA issue for more details
**Checklist**
> CSE-863 reintegrate missing fields

- CseEightselectBasic/Resources/views/backend/cse_eightselect_basic_attribute_config/view/list/eightselect_attribute.js
**Jira Issue**
https://8select.atlassian.net/browse/CSE-861
**Summary**
- show values beside labels in the dropdown selection of attribute mapping
**Checklist**
> CSE-861 show shopware attribute labels

- CseEightselectBasic/CseEightselectBasic.php
- CseEightselectBasic/Resources/views/backend/cse_eightselect_basic_manual_export/view/detail/export.js
**Jira Issue**
https://8select.atlassian.net/browse/CSE-1077
**Summary**
* fix update logic for export dir - because it was only executed if the current version was 1.0.2 - and that version never existed at all
* create table `8s_feeds` for all versions <= 1.5.0 
* fix typo in export timestamp sentence
**Checklist**
> CSE-1077 create 8s feeds on update

- .gitignore
- CseEightselectBasic/Resources/views/frontend/index/header.tpl
- dist/.gitignore
**Jira Issue**
https://8select.atlassian.net/browse/CSE-954
**Summary**
* deduplicate wgt-ldr loading
* query for tabs and content with `querySelector` to avoid duplicated code for `before` and `after` config
**Checklist**
> CSE-954 fix wrong tab selection

- CseEightselectBasic/Resources/views/backend/cse_eightselect_basic_attribute_config/view/list/eightselect_attribute.js
**Jira Issue**
https://8select.atlassian.net/browse/CSE-1088
**Summary**
- fixed conditional to check for label store to exist before accessing a label item in mapping modal 
**Checklist**
> CSE-1088 broken export mapping modal

- CseEightselectBasic/Resources/views/frontend/index/header.tpl
**Jira Issue**
https://8select.atlassian.net/browse/CSE-1091
**Summary**
* check for existence before accessing parentNode
**Checklist**
> CSE-1091 check for exisitence of containers before getting their parentNode

- CseEightselectBasic/Components/FieldHelper.php
- CseEightselectBasic/Components/PropertyExport.php
**Jira Issue**
https://8select.atlassian.net/browse/CSE-1270
**Summary**
Replace HTML tags in product descriptions with single spaces.
**Checklist**
> CSE-1270 Replace HTML tags with single spaces

- CseEightselectBasic/Resources/views/frontend/index/header.tpl
**Jira Issue**
https://8select.atlassian.net/browse/CSE-1320
**Summary**
* allow to update quantity via cart API
* use the Promise object and resolve after product was added to cart
**Checklist**
> CSE-1320 - fix addToCart: update quantity and return Promise

- bin/lib/build.sh
**Jira Issue**
https://8select.atlassian.net/browse/CSE-1216
**Summary**
* S3 bucket users where migrated to the product-feed-service
**Checklist**
> CSE-1216 use product-feed-service stack

- CseEightselectBasic/Resources/views/frontend/index/header.tpl
**Jira Issue**
https://8select.atlassian.net/browse/CSE-1358
**Summary**
- enclose all frontend function closures and if statements with semicolons according to ESLint standard
**Checklist**
> CSE-1358 add missing js semicolons

- CseEightselectBasic/Resources/views/frontend/detail/index.tpl
- CseEightselectBasic/Resources/views/frontend/index/header.tpl
**Jira Issue**
https://8select.atlassian.net/browse/CSE-1362
**Summary**
* add class to detect cse tab container
* detect previously active tab based on position 
**Checklist**
> CSE-1362 corect tab behaviour

- CseEightselectBasic/Resources/views/frontend/index/index.tpl
**Jira Issue**
https://8select.atlassian.net/browse/CSE-1408
**Summary**
* respect offcanvas cart setting from theme
**Checklist**
> CSE-1408 respect theme offcanvas cart setting

- CseEightselectBasic/Components/ArticleExport.php
- CseEightselectBasic/Components/Config.php
- CseEightselectBasic/Components/Export.php
- CseEightselectBasic/Components/ExportSetup.php
- CseEightselectBasic/Components/ForceFullPropertyExport.php
- CseEightselectBasic/Components/PropertyExport.php
- CseEightselectBasic/Controllers/Backend/CseEightselectBasicManualExport.php
- CseEightselectBasic/CseEightselectBasic.php
- CseEightselectBasic/Resources/services.xml
**Jira Issue**
https://8select.atlassian.net/browse/CSE-1504
**Summary**
* catch exception on trigger creation during install and fallback to full export
* add config table to save settings for plugin
* add daily cron for full property export
**Checklist**
> CSE-1504 fallback full export without db trigger

- CseEightselectBasic/Components/Export.php
**Jira Issue**
https://8select.atlassian.net/browse/CSE-1537
**Summary**
* ignore unmapped attributes
**Checklist**
> CSE-1537 ignore unmapped attributes

- CseEightselectBasic/Components/Export.php
- CseEightselectBasic/Components/FieldHelper.php
**Jira Issue**
https://8select.atlassian.net/browse/CSE-1562
**Summary**
* remove invalid (empty) filterIds
* additionally check for valid articleId and filterId to avoid invalid SQL
**Checklist**
> CSE-1562 - invalid sql due to filterId = null

- CseEightselectBasic/Components/AWSUploader.php
- CseEightselectBasic/Components/FieldHelper.php
- CseEightselectBasic/CseEightselectBasic.php
**Jira Issue**
https://8select.atlassian.net/browse/CSE-1579
**Summary**
* fallback to fullexport on any error during DB trigger creation
* push logs for plugin setup routines to AWS
**Checklist**
> CSE-1579 fallback to fullexport on all dbtrigger errors

- CseEightselectBasic/Components/ArticleImageMapper.php
- CseEightselectBasic/CseEightselectBasic.php
**Jira Issue**
https://8select.atlassian.net/browse/CSE-1593
**Summary**
- added `ORDER BY` condition to DB query in `ArticleImageMapper`
**Checklist**
> CSE-1593 respect sorting of variant mappings in article image mapper

- CseEightselectBasic/Components/FieldHelper.php
**Jira Issue**
https://8select.atlassian.net/browse/CSE-1592
**Summary**
- add `number` parameter with products `sku` (ordernumber) as additional parameter on product url assembly `getUrl()` in `FieldHelper.php`
**Checklist**
**Example CSV:**
https://productfeed-prod.staging.8select.io.s3.amazonaws.com/14b186e5-9279-48b9-b8a5-c313b51deaad/property_feed/2018/11/20/14b186e5-9279-48b9-b8a5-c313b51deaad_property_feed_1542720903764.csv
> CSE-1592 export product deeplinks

- CseEightselectBasic/Resources/views/frontend/index/header.tpl
**Jira Issue**
https://8select.atlassian.net/browse/CSE-1621
**Summary**
- wait for dom content to be loaded before activating tab
**Checklist**
> CSE-1621 wait for dom content to be loaded before activating tab

- CseEightselectBasic/Resources/views/emotion_components/backend/psp_psv.js
- CseEightselectBasic/Resources/views/emotion_components/backend/psp_tlv.js
- CseEightselectBasic/Resources/views/emotion_components/backend/sys_psv.js
**Jira Issue**
https://8select.atlassian.net/browse/CSE-1726
**Summary**
* remove comment block  - maybe something strange happens and the next js line is remove due to the previous line where we have a comment - not a block comment -> https://github.com/8select/shopware-plugin-sob/pull/76/files#diff-970725727dbec239a8e9dfd23479d916L2
**Checklist**
> remove comment block from emotion components

- CseEightselectBasic/Components/Export.php
**Jira Issue**
https://8select.atlassian.net/browse/CSE-1737
**Summary**
* `$i` was renamed to `$offset` in https://github.com/8select/shopware-plugin-sob/pull/75/files#diff-8d00cfd1c0612b454bce981dd2dcb8cbR210
**Checklist**
> CSE-1737 use $offset instead of non existing $i

- CseEightselectBasic/CseEightselectBasic.php
- CseEightselectBasic/Resources/views/emotion_components/widgets/emotion/components/psp_tlv.tpl
**Jira Issue**
https://8select.atlassian.net/browse/CSE-1695
**Summary**
- rename stylefactor occurrences into tags
**Checklist**
> CSE-1695 rename stylefactor to tags

- CseEightselectBasic/CseEightselectBasic.php
- CseEightselectBasic/Resources/services.xml
- CseEightselectBasic/Services/Dependencies/Provider.php
- CseEightselectBasic/Services/Export/Connector.php
- CseEightselectBasic/Services/Export/CseCredentialsMissingException.php
- CseEightselectBasic/Services/Export/Helper/ShopUrl.php
- CseEightselectBasic/Services/PluginConfig/PluginConfig.php
- CseEightselectBasic/Setup/Helpers/EmotionComponents.php
- CseEightselectBasic/Setup/Install.php
- CseEightselectBasic/Setup/Uninstall.php
- bin/lib/build.sh
**Jira Issue**
https://8select.atlassian.net/browse/CSE-1663
**Summary**
- send data on install/uninstall/activate/deactivate/config update
- fix some missing imports :see_no_evil:
**Checklist**
> CSE-1663 send shop info for export API

- bin/lib/build.sh
**Jira Issue**
https://8select.atlassian.net/browse/CSE-1804
**Summary**
* use replacement s3 user to rotate s3 credentials
**Checklist**
> CSE-1804 use replacement s3 user

- CseEightselectBasic/Components/PropertyExport.php
**Jira Issue**
https://8select.atlassian.net/browse/CSE-1817
**Summary**
* in #75 I forgot to add the `categoryID` to the non-delta property export query
**Checklist**
> CSE-1817 add missing category id to query

- CseEightselectBasic/Controllers/Frontend/CseEightselectBasic.php
- CseEightselectBasic/CseEightselectBasic.php
- CseEightselectBasic/Resources/services.xml
- CseEightselectBasic/Services/Dependencies/Provider.php
- CseEightselectBasic/Services/Export/Connector.php
- CseEightselectBasic/Services/PluginConfig/PluginConfig.php
- CseEightselectBasic/Setup/Helpers/Logger.php
- CseEightselectBasic/Setup/Uninstall.php
- bin/lib/build.sh
**Jira Issue**
https://8select.atlassian.net/browse/CSE-1714
**Summary**
* log installation routine details via shop-connector
* add plugin config to connector call
**Checklist**
> CSE-1714 log via api

- CseEightselectBasic/Services/Export/Connector.php
- CseEightselectBasic/Setup/Helpers/Logger.php
**Jira Issue**
https://8select.atlassian.net/browse/CSE-1663
**Summary**
* adjust tenant signature to match the TUS interface
**Checklist**
> CSE-1663 use TUS interface for tenant object

- CseEightselectBasic/Components/Export.php
- CseEightselectBasic/Services/Export/StatusExport.php
**Jira Issue**
https://8select.atlassian.net/browse/CSE-1844
**Summary**
* it is possible to make a product inactive and/or a variant
** in both cases the variant should not be buyable, i.e. `isInStock` should be `0`
**Checklist**
> CSE-1844 also check parent products active state

- CseEightselectBasic/Services/Export/Connector.php
**Jira Issue**
https://8select.atlassian.net/browse/CSE-1663
**Summary**
* somehow the `path` argument for the delete call was missing :(
**Checklist**
> CSE-1663 add missing path to delete call

- CseEightselectBasic/CseEightselectBasic.php
- CseEightselectBasic/Services/Export/Connector.php
- CseEightselectBasic/Setup/Helpers/Logger.php
- bin/lib/build.sh
**Jira Issue**
https://8select.atlassian.net/browse/CSE-1858
**Summary**
* the `base_url` was ignored in tests on SW 5.2.17 so I removed it and make the guzzle calls with the full url 
**Checklist**
> CSE-1858 do not use base url

- docs/de/installationsanleitung.md
- docs/en/installation.md
**Jira Issue**
https://8select.atlassian.net/browse/CSE-1735 
**Summary**
* update docs
**Checklist**
> CSE-1735 remove CRON info from docs

- CseEightselectBasic/Services/Export/RawExport.php
**Jira Issue**
https://8select.atlassian.net/browse/CSE-1835
**Summary**
* this provides much cleaner filter options for product categories because there is only one product detail named `Kategorie` with multiple values
**Checklist**
> CSE-1835 add categories as list of category paths

- CseEightselectBasic/Services/Export/RawExport.php
**Jira Issue**
https://8select.atlassian.net/browse/CSE-1835
**Summary**
* `s_filters_articles` has a reference to `s_articles` and not `s_articles_details` 🤦‍♂️ 
**Checklist**
> CSE-1835 use s_articles.id to join s_filters_articles

- CseEightselectBasic/Controllers/Frontend/CseEightselectBasic.php
- CseEightselectBasic/Resources/views/frontend/index/header.tpl
- CseEightselectBasic/Services/Config/Validator.php
* add plugin version as comment and in config object even if plugin is inactive - this should not have been silenced before
* add endpoint to validate config
Summarize what you have done and why you have done it the way you did.
**Checklist**
> Add debug output for version and config

- CseEightselectBasic/Controllers/Frontend/CseEightselectBasic.php
* fix action name in whitelisted actions - it is late :(
**Checklist**
> whitelist correct action

- CseEightselectBasic/Services/Export/RawExport.php
**Summary**
* if a product has multiple category paths only the last was exported, because of https://github.com/8select/shopware-plugin-sob/blob/b2e827a41c35d142b0706c679f7b1de2a66d9b14/CseEightselectBasic/Services/Export/RawExport.php#L294
**Checklist**
> export all categories

- CseEightselectBasic/Services/Export/RawExport.php
**Summary**
* this will remove duplicate category paths
* if a product is in multiple categories that have the same parent / root there would have been duplicate paths
```
Deutsch -> Bekleidung -> Herren
Deutsch -> Bekleidung -> Damen
```
```
Deutsch
Deutsch -> Bekleidung
Deutsch -> Bekleidung -> Herren
Deutsch
Deutsch -> Bekleidung
Deutsch -> Bekleidung -> Damen
```
```
Deutsch
Deutsch -> Bekleidung
Deutsch -> Bekleidung -> Herren
Deutsch -> Bekleidung -> Damen
```
**Checklist**
> return unique category paths

- CseEightselectBasic/Setup/Updates/Update_2_0_0.php
**Summary**
In plugin version < 2.0.0 the plugin added DB triggers to log changed articles.
In 2.0.0 we dropped those triggers completely. Under some circumstances the DB user is not allowed to create or drop triggers. Therefor the update script failed, even if there where no triggers installed.
This can happen if MySQL's binlog is active and the DB user that Shopware is using does not have SUPER privileges.
On installation of plugin version < 2.0.0 we catched the exception that was thrown when the DB user was not able to install the triggers and disabled the delta export. This should have been done in the update script for 2.0.0 as well. We forgot this use case 🙈 
In order to circumvent this in the future, we now do the following:
- test if we even need to drop DB triggers with a simple …
> only drop old DB triggers if they exist

- CseEightselectBasic/Controllers/Frontend/CseEightselectBasic.php
- CseEightselectBasic/Resources/services.xml
- CseEightselectBasic/Services/Export/Attributes.php
- CseEightselectBasic/Services/Export/Connector.php
- CseEightselectBasic/Services/Export/RawExport.php
- CseEightselectBasic/Services/Export/VariantDimensions.php
- bin/lib/build.sh
- bin/lib/common.sh
- bin/release.sh
**Jira Issue**
https://8select.atlassian.net/browse/CSE-2058
**Summary**
* add APIs that return all possible product-attributes and variant-dimensions
those APIs are invoked by the product-mapping-service to serve values to the MCON for the modules "settings -> variants" and "settings -> addons"
**Checklist**
> CSE-2058 api for product attributes and dimensions

- CseEightselectBasic/Controllers/Frontend/CseEightselectBasic.php
- CseEightselectBasic/Resources/services.xml
- CseEightselectBasic/Services/Export/Attributes.php
- CseEightselectBasic/Services/Export/Helper/Fields.php
- CseEightselectBasic/Services/Export/Helper/ProductImages.php
- CseEightselectBasic/Services/Export/RawExport.php
- CseEightselectBasic/Services/Export/RawExportMapper.php
- bin/copy2dev.sh
**Jira Issue**
https://8select.atlassian.net/browse/CSE-2056
**Summary**
* return all product attributes in export with format `raw`
** use real column names whenever possible
* disallow export format `etl` and `property`
**Checklist**
> CSE-2056 return all product attributes in raw export

- CseEightselectBasic/Services/Config/Validator.php
- CseEightselectBasic/Setup/Install.php
- CseEightselectBasic/Setup/Uninstall.php
**Jira Issue**
https://8select.atlassian.net/browse/CSE-2072
**Summary**
we no longer need to configure the configurator group
that should be used at 8select
**Checklist**
> CSE-2072 remove variant attribute config requirement

- docs/de/installationsanleitung.md
- docs/en/installation.md
**Jira Issue**
https://8select.atlassian.net/browse/CSE-2113
**Summary**
* update installation instructions according to 3.0.0
**Checklist**
> CSE-2113 remove size attributes and attribute mapping from setup instructions

- CseEightselectBasic/Resources/views/frontend/index/index.tpl
**Shopware Issue**
- Shopware Plugin Support Ticket CSE-24594 
- https://account.shopware.com/producer/support/24594
**Summary**
- add translatable text snippet to hidden cart button to improve accessibility
- official docs for text snippet integration see: https://developers.shopware.com/designers-guide/snippets/
**Checklist**
> CSE-24594 add text snippet to hidden cart form button

- CseEightselectBasic/Services/Dependencies/Provider.php
- bin/copy2dev.sh
- bin/lib/build.sh
- bin/lib/common.sh
- bin/release.sh
You can use this to define the used AWS stage and also to have the Plugin use a custom host, for example from ngrok.
> allow to specify the AWS stage and custom host for release

- CseEightselectBasic/Controllers/Frontend/CseEightselectBasic.php
- CseEightselectBasic/CseEightselectBasic.php
- CseEightselectBasic/Resources/services.xml
- CseEightselectBasic/Services/Dependencies/Provider.php
- CseEightselectBasic/Services/Export/Attributes.php
- CseEightselectBasic/Services/Export/Connector.php
- CseEightselectBasic/Services/Migration/AttributeMapping.php
- CseEightselectBasic/Services/Migration/VariantDimensions.php
- CseEightselectBasic/Setup/Helpers/MenuEntry.php
- bin/lib/build.sh
- bin/lib/common.sh
- bin/release.sh
**Jira Issue**
https://8select.atlassian.net/browse/CSE-2072
**Summary**
The product and export configuration of CSE was moved to the MCON.
This PR adds endpoints that are used during migration progress to copy the product and export configuration from the Shopware plugin to the CSE.
**Checklist**
> CSE-2072 migration from 2.x to 3.x

- CseEightselectBasic/Resources/views/frontend/index/header.tpl
**Jira Issue**
https://8select.atlassian.net/browse/CSE-2581
**Summary**
- added HTML container content from smarty variable and append it to widget container at css selector
**Checklist**
Live-Demo:
http://shopware-5-2-17-php7.staging.8select.io/hoehenluft-abenteuer/fashion/herren/jacken/168/demo-shirt?c=5
Plugin-Config:
Frontend-Output:
> CSE-2581 respect custom html container content in on position css selector

- CseEightselectBasic/CseEightselectBasic.php
- CseEightselectBasic/Resources/views/frontend/index/header.tpl
Shopware support ticket CSE-28886
**Summary**
- do not click CSE tab on mobile to avoid unexpected behaviour
- only schedule to clear HTTP cache as the default update behaviour
**Checklist**
> Shopware support ticket - CSE-28886 - avoid clicking CSE tab on mobile

- bin/lib/build.sh
- bin/lib/common.sh
- bin/release.sh
this will allow external users to create a
distribution package of the plugin
> allow to override shop connector API

- CseEightselectBasic/Controllers/Frontend/CseEightselectBasic.php
I forgot to remove some debug output 🙈
> remove debug log output

- .github/PULL_REQUEST_TEMPLATE.md
- CseEightselectBasic/CseEightselectBasic.php
**Jira Issue**
https://8select.atlassian.net/browse/HX-735
**Summary**
regardless of the previously installed version we want to send
an update to the CSE
**Checklist**
> HX-735 connect plugin to CSE on any update

- CseEightselectBasic/Services/Export/RawExport.php
- CseEightselectBasic/Services/Export/StatusExport.php
**Jira Issue**
https://8select.atlassian.net/browse/HX-733 
**Summary**
currently the CSE can only be active for one shop
so we also need to use the price of the customergroup
that belongs to this shop
**Checklist**
> HX-733 use article price from customer group of active shop

- CseEightselectBasic/Services/Export/RawExport.php
- CseEightselectBasic/Services/Export/StatusExport.php
**Jira Issue**
https://8select.atlassian.net/browse/HX-733
**Summary**
Shopware subshops or language shops can have different price groups. 
Articles may have defined a price for all existing price groups. If there is no price set for a specific price group for an article the default price group "EK" is used for that article.
**Checklist**
> HX-733 return default price if no other set

- CseEightselectBasic/Services/Export/RawExport.php
- CseEightselectBasic/Services/Export/StatusExport.php
**Jira Issue**
https://8select.atlassian.net/browse/HX-740
**Summary**
Due to Corona VAT is reduced to 16% / 5%.
Applying the changed tax in SW is possible in many ways.
One way we need to support is via tax rules.
This change will take tax rules set for customer groups
into account.
The change also takes care of items without a price. Those prices are seen as `0` - the same way Shopware handles those prices.
**Checklist**
> HX-740 take tax rules into account

- CseEightselectBasic/Services/Export/RawExport.php
**Jira Issue**
https://8select.atlassian.net/browse/HX-811
**Summary**
SW 5.4 added the laststock option on a variant level. See https://developers.shopware.com/developers-guide/shopware-5-upgrade-guide-for-developers/#sold-out-variants
This PR will also respect the variant settings and therefor will export the correct value for our isInStock flag. 
**Checklist**
> HX-811 respect s_articles_details.laststock for SW >= 5.4
