8select/shopware-plugin-sob

CseEightselectBasic/Resources/config.xml
CseEightselectBasic/Resources/views/frontend/detail/index.tpl

**Jira Issue**
https://8select.atlassian.net/browse/CSE-880
**Summary**
- set default values for the widget output position on install (before the empty position options would cause shopware standard blocks to not be rendered in the frontend)
- removed left over closing if tag in the plugins smarty template
- fix code indent for template
**Checklist**

CSE-880 productinfo output hotfix

---

CseEightselectBasic/Components/ArticleExport.php
CseEightselectBasic/Components/FeedLogger.php
CseEightselectBasic/Components/QuickUpdate.php
CseEightselectBasic/Controllers/Backend/CseEightselectBasicManualExport.php
CseEightselectBasic/CseEightselectBasic.php
CseEightselectBasic/Resources/views/backend/cse_eightselect_basic_manual_export/view/detail/export.js
CseEightselectBasic/Resources/views/backend/cse_eightselect_basic_manual_export/view/detail/window.js

**Jira Issue**
https://8select.atlassian.net/browse/CSE-884
**Summary**
- added new component `FeedLogger.php` / class `FeedLogger`
- create new database table `8s_feeds` to store timestamps upon installation
- show datetime of last updates for both Full Export and Quick Update in manual export modal
**Checklist**
**Before any exports did run (after fresh plugin installation):**
**After Exports have been executed:**

CSE-884 show timestamp of last export update

---

CseEightselectBasic/Controllers/Backend/CseEightselectBasicAttributeConfig.php

**Jira Issue**
https://8select.atlassian.net/browse/CSE-1096
**Summary**
- added missing table names in `CseEightselectBasicAttributeConfig.php` Backend Controller
There are no selectable mapping fields without a corresponding table anymore now.
**Checklist**

CSE-1096 add missing table names on standard mapping fields

---

CseEightselectBasic/Components/ArticleExport.php
CseEightselectBasic/Components/ArticleImageMapper.php
CseEightselectBasic/Components/FieldHelper.php
CseEightselectBasic/Components/RunCronOnce.php
CseEightselectBasic/Resources/views/frontend/index/header.tpl

**Jira Issue**
https://8select.atlassian.net/browse/CSE-988
**Summary**
- added `ArticleImagerMapper` class that...
- ...gets the current articles images by its ordernumber
- ...checks the current article images for existing option mappings and matches them with the articles own options
- will return the `img` and `extension` of any image which contains an option mapping that matches an option of its article / variant 
- sort images by their respective `position` (resolves https://8select.atlassian.net/browse/CSE-1036)
- reduced DB queries as far as possible by batch querying more data upfront
- remove unnecessary spaces around pipes between image urls
For more information on how option relations between articles an images are achieved, see JIRA ticket.
**Checklist**
**Example Export see …

CSE-988 export variant images

---

CseEightselectBasic/Resources/views/frontend/index/header.tpl

**Jira Issue**
https://8select.atlassian.net/browse/CSE-1321
**Summary**
* do not rely on active tab-name or description to be the active selection
* use `is--active` class to determine which tab and description should be hidden on `showSys` and showed on `hideSys`
**Checklist**

CSE-1321 store activeTab based on is--active classname

---

CseEightselectBasic/Components/ExportSetup.php
CseEightselectBasic/CseEightselectBasic.php

**Jira Issue**
https://8select.atlassian.net/browse/CSE-1323
**Summary**
before this change every trigger added a row in the update queue table
this can result in quadtrillion entries that take much disk space if the
propert_export cron was not working, i.e. the table was never emptied
with this change the max number of entries equals the entries in the
s_articles_details table and therefor the table needs less memory than
the s_articles_details table because there are only 2 rows to fill
**Checklist**

CSE-1323 make entries in update queue unique

---

CseEightselectBasic/Resources/views/frontend/index/header.tpl

**Jira Issue**
https://8select.atlassian.net/browse/CSE-1326
**Summary**
- dispatch `MouseEvent('click')` on active Tab as soon as DOM is ready and SYS endpoint responded
- removed active Tab setter by `elem.classList` attribute
**Notes**
Previously we have set the active tab by manipulating the `classList` attribute on the Tab DOM element we wanted to activate. However this didn't seem to convince the existing tab navigation logic of another tab being activated, which resulted in the user not being able to activate the first tab (which internally was already the active one). By dispatching an actual click event on our target tab we trigger the native tab navigation logic instead of implementing our own. 
**Checklist**

CSE-1326 fix tab navigation

---

CseEightselectBasic/Components/Export.php

**Jira Issue**
https://8select.atlassian.net/browse/CSE-1351
**Summary**
* you can define price/customer groups in shopware
* a product can have different prices for each of those groups
* this PR limits the used price to the default group, otherwise we export multiple lines per product
**Checklist**

CSE-1351 only use default pricegroup

---

CseEightselectBasic/Resources/views/frontend/index/header.tpl

**Jira Issue**
https://8select.atlassian.net/browse/CSE-1362
**Summary**
* hide sys tab on startup
* excluding scripts / templates based on preview mode is very complicated, because if statements can only exist inside smarty `block` elements - that would result in massive amounts of if statements, this is the "easy" way
**Checklist**

CSE-1362 initially call hideSys() to make default tab active

---

CseEightselectBasic/Resources/views/frontend/index/header.tpl

**Jira Issue**
https://8select.atlassian.net/browse/CSE-1570
**Summary**
- we check for standard shopware cart form to exist and if so, use it for cart events of our widget
- use our own `eightselect_cart_trigger_form` only if no standard shopware cart form is available
Using the standard shopware cart if possible prevents other third party Shopware Plugins that may manipulate cart evetns from interfering with our very own cart form.
**Checklist**
+ tested with [Custom Products ](https://store.shopware.com/swagcustomproducts/custom-products.html)Plugin in Staging Testshop
+ tested without Shopware Standrad cart form (Einkaufswelten Integration)

CSE-1570 prevent multiple cart events

---

CseEightselectBasic/Resources/views/frontend/index/header.tpl

**Jira Issue**
https://8select.atlassian.net/browse/CSE-1578
**Background**
- referencing the `input` elements from the `eightselectCartForm` didn't work because we were mixing up `getElementById` and `querySelector` DOM queries
**Summary**
- use `querySelector` only because you're not supposed to do such nasty things
**Checklist**
Vorher:

CSE-1578 fix cart function outside details page

---

CseEightselectBasic/Resources/views/frontend/index/header.tpl
CseEightselectBasic/Resources/views/frontend/index/index.tpl

**Jira Issue**
https://8select.atlassian.net/browse/CSE-1590
**Summary**
* currently our cart logic interferes with plugins that also make use of the default shopware cart form
* instead of adding a second active cart form we now initially add our cart form without swAddArticle plugin triggers and without named input elements for ordernumber `sAdd` and quantitiy `sQuantity`
* the correct configuration and the `swAddArticle()` plugin are triggered while something is added to
the cart via our widgets now - our cart form is reset afterwards to avoid any inteference with other plugins
* incomplete list of plugins that intefered with the old logic:
* Custom Products
* Produkt Bundles
**Checklist**

CSE-1590 add our cart form without swAddArticle plugin triggers

---

CseEightselectBasic/Components/AWSUploader.php
CseEightselectBasic/Components/ArticleExport.php
CseEightselectBasic/Components/Export.php
CseEightselectBasic/Components/ForceFullPropertyExport.php
CseEightselectBasic/Components/PropertyExport.php
CseEightselectBasic/Components/RunCronOnce.php
CseEightselectBasic/CseEightselectBasic.php

**Jira Issue**
https://8select.atlassian.net/browse/CSE-1617
**Summary**
* in order to avoid file access problems we let PHP create a tempfile in a location it has writeaccess
* add `files/8select/` dir as fallback within shopware installation directory
* the alternative was to use stream but that got very complicated, because we would have to change the feed processing too (reacting to s3 putobject event, s3 bucket access policy)
**Checklist**

CSE-1617 use temp file created by PHP

---

CseEightselectBasic/Components/ConfigValidator.php
CseEightselectBasic/Controllers/Backend/CseEightselectBasicConfigValidation.php
CseEightselectBasic/CseEightselectBasic.php
CseEightselectBasic/Resources/config.xml
CseEightselectBasic/Resources/views/frontend/checkout/ajax_add_article.tpl
CseEightselectBasic/Resources/views/frontend/index/header.tpl

**Jira Issue**
https://8select.atlassian.net/browse/CSE-1409
**Summary**
- call `_8select.initCSE()` in cart confirmation modal when SYS-ACC is enabled in plugin config
- added plugin config option to add a custom HTML container for SYS-ACC
**Checklist**
Live-Demo at: http://shopware.staging.8select.io:8080/
**New Config Option:**
**Example - HTML-Container headline in PSV**
**Example - HTML-Container headline in SYS-ACC**
**Example - with SYS-ACC:**
**Example - without SYS-ACC (default Shopware cross-selling):**

CSE-1409 enable sys acc

---

CseEightselectBasic/Resources/views/emotion_components/backend/psp_psv.js
CseEightselectBasic/Resources/views/emotion_components/backend/psp_tlv.js
CseEightselectBasic/Resources/views/emotion_components/backend/sys_psv.js

**Jira Issue**
https://8select.atlassian.net/browse/CSE-1726
**Summary**
this seems to be necessary sometimes
we just do like the docs say:
https://developers.shopware.com/developers-guide/custom-shopping-world-elements/#advanced:-adding-a-custom-emotion-component-in-extjs
**Checklist**

CSE-1726 add commented smarty blocks to emotion ExtJS

---

CseEightselectBasic/CseEightselectBasic.php
CseEightselectBasic/Resources/services.xml
CseEightselectBasic/Subscriber/TemplateRegistration.php

**Jira Issue**
https://8select.atlassian.net/browse/CSE-1732
**Summary**
* use extra subscriber class to register smarty template dir - this is exactly what Shopware does in it's [example plugin](https://developers.shopware.com/developers-guide/example-plugin/#register-template-first)
**Checklist**

CSE-1732 add template dir via extra subscriber class

---

CseEightselectBasic/phpunit.xml.dist
CseEightselectBasic/tests/Functional/Bootstrap.php
CseEightselectBasic/tests/Unit/Services/Export/Helper/ProductPriceTest.php
README.md

**Jira Issue**
https://8select.atlassian.net/browse/CSE-836
**Summary**
- added a `phpunit.xml.dist` file to setup executable paths for phpunit
- added `tests` directory to plugin files, containing a `Bootstrap.php` to initialize shopware's kernel
- added a basic test file for `Services/Export/Helper/ProductPrice.php`
- **Note**: this test is setup to work with PHP 7.0 and PHPunit 6 or higher, see also https://github.com/symfony/symfony/issues/21816#issuecomment-283381522
- added instructions for running phpunit tests to the readme file
**Checklist**
**Failing PHP Unit Test:**
**Passing PHP Unit Test:**

CSE-836 php unit tests

---

CseEightselectBasic/Controllers/Frontend/CseEightselectBasic.php
CseEightselectBasic/Services/Export/Helper/Mapper.php

**Jira Issue**
https://8select.atlassian.net/browse/CSE-1874
**Summary**
* some time ago we tried to be smart about utf8 and failed - we where destroying valid utf8 chars
* this PR change the formatting of product description to that only html entities are removed and nothing more, the rest is done in the product-puller service, i.e. removal of line breaks and consecutive whitespaces
**Checklist**

CSE-1874 do not destroy utf8 chars

---

CseEightselectBasic/Controllers/Frontend/CseEightselectBasic.php
CseEightselectBasic/Resources/services.xml
CseEightselectBasic/Services/Export/RawExport.php
CseEightselectBasic/Services/Export/RawExportMapper.php

**Jira Issue**
https://8select.atlassian.net/browse/CSE-1835
**Summary**
In order to use dynamic product-sets without the need of attribute-normalisation and outside the fashion scope, we allow to filter products based on their details. Those details are exported with values as is and are give a name that corresponds to the source table in Shopware.
* export product data in new `productDetail` format
* initially we export a basic set of data, this can be extended anytime
**Checklist**

CSE-1835 export raw product-data for dynamic productsets outside fashion scope

---

CseEightselectBasic/Resources/views/frontend/detail/index.tpl
CseEightselectBasic/Resources/views/frontend/index/header.tpl

**Jira Issue**
https://8select.atlassian.net/browse/CSE-1918
**Summary**
General:
- updated `8s_preview_mode_enabled` smarty config key to `CseEightselectBasicPreviewActive` in templates
IF widget position "Produkttabs" is active in plugin config:
- always activate first _**visible**_ tab (instead of first tab present in DOM) as long as no valid set is available
IF preview mode is active and preview query string parameter is missing
- exclude cse-tab and cse-tab-content from DOM
- exclude tab related JS logic from DOM 
This prevents:
- invisible tabs (like the cse tab) being activated in tab navigation if no valid set is available
- tab related logic from being executed in preview mode when the corresponding query parameter is missing
**Checklist**

CSE-1918 activate description tab in preview mode

---

CseEightselectBasic/Services/Export/Helper/Mapper.php

**Summary**
add extra space to make sure words are separated by spaces
**example**
"beschreibung": "Keine Beschreibung vorhanden, diese folgt in Kürze.<br />Stand: Update vom 2019-03-01 20:46",
"beschreibung1": "Keine Beschreibung vorhanden, diese folgt in Kürze.Stand: Update vom 2019-03-01 20:46",
"Kürze.Stand" should be two words not one
that's why we add another space
**Checklist**

add extra space to make sure words are separated by spaces

---

CseEightselectBasic/CseEightselectBasic.php
CseEightselectBasic/Resources/views/frontend/checkout/finish.tpl

**Jira Issue**
https://8select.atlassian.net/browse/CSE-1878
**Summary**
* currently we use the basket item price for the checkout tracking
* this price is based on the currency the customer has chosen
* we need to use the normalized price that is used during product export
* the change will produce wrong prices in some cases, because the basket item
price only has 2 digit precision
example:
base price: 19.99
current currency factor: 0.5
basket price: 9.99
tracked price: 19.98
**Checklist**

CSE-1878 use normalized price in checkout tracking

---

CseEightselectBasic/CseEightselectBasic.php

**Jira Issue**
https://8select.atlassian.net/browse/CSE-2072
**Summary**
Existing customers data has to be migrated - to save time now we do not implement any migration step. Therefor existing customers are not allowed to upgrade to 3.x
**Checklist**

CSE-2072 disable upgrade to 3.x

---

CseEightselectBasic/Services/Export/Attributes.php

as brand is one of the obligatory fields for the fashion addon this has to be accessible inside the attribute mapping

add supplier name to list of attributes

---

CseEightselectBasic/Services/Export/Attributes.php
CseEightselectBasic/Services/Export/RawExport.php

- it may happen, that `s_articles_attributes` is missing a column that is still defined in `s_attribute_configuration` - therefor we only return attributes that exist in `s_articles_attributes``
- `s_filter_options.name` or `s_attribute_configuration.label` may be empty or `NULL` - as we really like to have a label, we use the slug as a fallback

ignore unknown attributes and fallback to slug if label is empty

---

CseEightselectBasic/Resources/config.xml
CseEightselectBasic/Resources/views/frontend/index/header.tpl

**Jira Issue**
https://8select.atlassian.net/browse/CSE-2308
**Summary**
- added new selection "CSS selector" to existing plugin config option "SYS-PSV: Position where the widget will be placed"
- added new plugin config option "CSS selector"
- dynamically inject widget at given CSS selector, while respecting:
- preview mode
- block start or end position
**Checklist**
- [x Unit tests for new / changed logic exist OR no logic changes are passing
**Example Setting:**
**Results in:**
**If CSS selector does not exist, see JS console:**

CSE-2308 allow dynamic positioning for SYS-PSV

---

CseEightselectBasic/Resources/views/frontend/index/header.tpl

**Jira Issue**
https://8select.atlassian.net/browse/CSE-2308
**Summary**
- follow-up for https://github.com/8select/shopware-plugin-sob/pull/115
- try / catch query selection if position is "CSS selector" but none was provided in plugin config 
**Checklist**
**1. In Plugin Configuration (admin panel):**
**2. In JS Console (store front):**

CSE-2308 try-catch missing css selector

---

CseEightselectBasic/Services/Export/RawExport.php

**Summary**
categories with only one level do not have a path
in shopwares article-category structure
therefor those where null before
**Checklist**

export article categories that only have one level

---

CseEightselectBasic/CseEightselectBasic.php
CseEightselectBasic/Resources/views/frontend/index/header.tpl

Shopware support ticket CSE-28886
**Summary**
- do not click CSE tab on mobile to avoid unexpected behaviour
- schedule to clear all frontend caches as the default update behaviour
- this PR handles the `hideSys` event that was forgotten in https://github.com/8select/shopware-plugin-sob/pull/123
**Checklist**

Shopware support ticket - CSE-28886 - avoid clicking CSE tab on mobile on hideSys event

---

CseEightselectBasic/Resources/views/frontend/index/header.tpl

**Shopware Support Issue**
CSE-28886
**Summary**
follow up on #123 and #124 
before we can actually check via element.offsetHeight if the
element is currently visible we need to try to make it visible
i.e. remove display:'none'
that way the element is visible on desktop client but not on mobile clients
(SW logic)
after setting display:'' we check if the element is actually there,
and it will not be there on mobile devices because it will still be hidden via other responsive stylesheets
**Checklist**

CSE-28886 "unhide" tab element before checking if it is visible

---

CseEightselectBasic/Controllers/Frontend/CseEightselectBasic.php
CseEightselectBasic/Services/Export/Helper/ProductImages.php
bin/lib/build.sh

To workaround the situation where image data seems corrupt because `original` is just missing, we use the last entry in the images entry, hoping that this is the biggest thumbnail. 🙈 
Additionally the API will now return the current plugin version in a header field. This way we can see which plugin version the tenant is using directly via the API response. QOL!

Missing images

---

CseEightselectBasic/Controllers/Frontend/CseEightselectBasic.php
CseEightselectBasic/Services/Export/RawExport.php

Add  `filter` param to products API and a first filter that allows to return a specific product by sku.
This is mainly used to take a look at specific products to understand product data a shop is currently sending.

allow to filter for SKU

---

CseEightselectBasic/CseEightselectBasic.php
CseEightselectBasic/Services/Export/Connector.php
CseEightselectBasic/Services/Export/CseCredentialsMissingException.php

**Jira Issue**
https://8select.atlassian.net/browse/HX-735
**Summary**
in some scenarios a shop just disconnected from CSE because there
was a deployment going on and plugins got disabled and enabled again.
to avoid such scenarios we now "lock" a tenant connection to the CSE
and only allow to disconnect the shop manually or via data-reset.
if the plugin is disabled/deinstalled the only thing that will happen
to the shop while it is not disconnected is just a HTTP request
to pull products that will go into nirvana because the plugin is not
installed anymore, i.e. the endpoint the product export is targeting is
not there.
**Checklist**

HX-735 do not disconnect from CSE anymore

---

CseEightselectBasic/Services/Export/StatusExport.php

**Jira Issue**
https://8select.atlassian.net/browse/HX-740
**Summary**
The query syntax was wrong - the double quotes around parameters are wrong.
Doctrine will add quotes when using parameters.
:see_no_evil:
**Checklist**

HX-740 remove duplicated quotes from doctrine query

---

CseEightselectBasic/Controllers/Frontend/CseEightselectBasic.php
CseEightselectBasic/Resources/services.xml
CseEightselectBasic/Services/Export/RawExport.php
CseEightselectBasic/Services/Export/StatusExport.php
CseEightselectBasic/Services/Export/StatusExportMapper.php

**Jira Issue**
https://8select.atlassian.net/browse/HX-586
**Summary**
Products API:
* format `'status'` is not supported anymore
* instead, format `'raw'` is now supported with delta flag: It delivers the same data as `'status'` before, but in the raw data format which is expected by the latest version of [product-puller](https://github.com/8select/lambda-product-puller) (underlying implementation is identical to before, except for formatting of prices)
**Checklist**

HX-586 Harmonize product status updates process

---

CseEightselectBasic/CseEightselectBasic.php
CseEightselectBasic/Resources/views/emotion_components/widgets/emotion/components/psp_psv.tpl
CseEightselectBasic/Resources/views/emotion_components/widgets/emotion/components/psp_tlv.tpl
CseEightselectBasic/Resources/views/emotion_components/widgets/emotion/components/sys_psv.tpl
CseEightselectBasic/Resources/views/frontend/checkout/ajax_add_article.tpl
CseEightselectBasic/Resources/views/frontend/detail/custom/cse.tpl
CseEightselectBasic/Resources/views/frontend/detail/index.tpl
CseEightselectBasic/Resources/views/frontend/index/header.tpl
CseEightselectBasic/Services/PluginConfig/PluginConfig.php

- SW default shop is the Shop that is created during SW installation (id = 1)
- most code in shopware with Shop/shopId uses either this default shop as the default or as the default parameter
- when the default shop is not id=1 then the Plugin Config logic seems broken and values are not saved for all shops
To handle this we always use the config of the default shop instead of the current shop.
**Checklist**

always use plugin config of default shop
